<?php
/**
 * Processes theme assets and returns their properties for registering and enqueuing
 *
 * Note: Do NOT edit this file to add assets. Do that in the `inc/assets-config.php` file.
 *
 * @package CassidyDC\BlockTheme\Functions
 * @version 1.0.0
 */

declare( strict_types = 1 );
namespace CassidyDC\BlockTheme;

/**
 * Processes theme assets properties
 *
 * @since 1.0.0
 * @param array<mixed> $assets_config A list of theme assets config settings.
 * @return array<mixed> A list of theme assets properties.
 */
function process_theme_assets( array $assets_config ): array {
	$asset_type = $assets_config['type'];
	$asset_dir  = match ( $asset_type ) {
		'style'            => 'build/css',
		'script'           => 'build/js',
		'editor_ui_style'  => 'build/css/blocks',
		'editor_ui_script' => 'build/js/blocks',
		default            => 'build'
	};
	$is_script_type = in_array( $asset_type, [ 'script', 'editor_ui_script' ], true );
	$assets_props   = [];

	foreach ( $assets_config['assets'] as $asset => $properties ) {
		$asset_filename = $properties['file'];
		$asset_basename = pathinfo( $asset_filename, PATHINFO_FILENAME );
		$asset_path     = "/{$asset_dir}/{$asset_filename}";
		$asset_handle   = $properties['handle'] ?? null;
		$asset_category = $properties['cat'] ?? null;
		$is_library_cat = $asset_category === 'library';

		// If it exists, retrieves the `.asset.php` file generated by the WP build script process.
		$php_asset_path = get_theme_file_path( "/{$asset_dir}/{$asset_basename}.asset.php" );
		$php_asset      = file_exists( $php_asset_path ) ? require $php_asset_path : null;

		// Sets handle value.
		if ( $asset_handle ) {
			$handle = $asset_handle;
		} else {
			$handle = $is_library_cat ? $asset_basename : HANDLE_PREFIX . '-' . $asset_basename;
		}

		// Sets last_prop value.
		if ( $is_script_type ) {
			$args = $properties['args'] ?? match ( $asset_type ) {
				'script' => [
					'in_footer' => false,
					'strategy'  => 'defer',
				],
				default => false,
			};
			$last_prop = [
				'key'   => 'args',
				'value' => $args,
			];
		} else {
			$media     = $properties['media'] ?? 'all';
			$last_prop = [
				'key'   => 'media',
				'value' => $media,
			];
		}

		// Sets other property values.
		$src  = get_theme_file_uri( $asset_path );
		$deps = $properties['deps'] ?? $php_asset['dependencies'] ?? [];
		$ver  = $php_asset['version'] ?? filemtime( get_theme_file_path( $asset_path ) );

		// Adds asset's properties to return array.
		$assets_props[] = [
			'handle'          => $handle,
			'src'             => $src,
			'deps'            => $deps,
			'ver'             => $ver,
			$last_prop['key'] => $last_prop['value'],
		];
	}

	return $assets_props;
}

/**
 * Processes editor stylesheets' properties
 *
 * @since 1.0.0
 * @param array<string[]> $editor_styles_config A list of editor stylesheet config settings.
 * @return array<string> An array of Editor stylesheet path strings for `add_editor_style()`.
 */
function process_editor_styles( array $editor_styles_config ): array {
	$asset_dir    = 'build/css';
	$assets_paths = [];

	foreach ( $editor_styles_config as $asset => $properties ) {
		$asset_path = "{$asset_dir}/{$properties['file']}";

		// Add asset's path to return array.
		$assets_paths[] = $asset_path;
	}

	return $assets_paths;
}

/**
 * Processes block stylesheets' properties
 *
 * No configurable options are used to generate the block stylesheets as they
 * are automatically pulled from the theme files structure.
 *
 * @since 1.0.0
 * @return array<mixed> A list of block stylesheet properties.
 */
function process_block_styles(): array {
	$asset_dir    = 'build/css/blocks';
	$assets_props = [];

	// Get all block directories (namespaces).
	foreach ( glob( get_theme_file_path( $asset_dir . '\/*/' ) ) as $block_path ) {
		$block_namespace = basename( $block_path );

		// Get all blocks in each block directory (namespace).
		foreach ( glob( $block_path . '*.css' ) as $block_file_path ) {
			$block_name = basename( $block_file_path, '.css' );
			$args       = [
				'handle' => HANDLE_PREFIX . "-{$block_namespace}-{$block_name}",
				'src'    => get_theme_file_uri( "{$asset_dir}/{$block_namespace}/{$block_name}.css" ),
				'path'   => $block_file_path,
				'ver'    => filemtime( $block_file_path ),
			];

			// Add asset's properties to return array.
			$assets_props[] = [
				'name' => "{$block_namespace}/{$block_name}",
				'args' => $args,
			];
		}
	}

	return $assets_props;
}
